// <auto-generated />
using System;
using AiSoftwareFactory.Agents.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiSoftwareFactory.Agents.Migrations
{
    [DbContext(typeof(AppDbContextPlateforme))]
    [Migration("20260721222500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiSoftwareFactory.Agents.Models.HistoriqueValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime2");

                    b.Property<int>("Etape")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjetId");

                    b.ToTable("HistoriqueValidations");
                });

            modelBuilder.Entity("AiSoftwareFactory.Agents.Models.Projet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EtapeActuelle")
                        .HasColumnType("int");

                    b.Property<string>("IdeeMetier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatAnalyse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatArchitecture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatDevBackend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatDevFrontend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultatDevOps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatutEtapeActuelle")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("AiSoftwareFactory.Agents.Models.HistoriqueValidation", b =>
                {
                    b.HasOne("AiSoftwareFactory.Agents.Models.Projet", null)
                        .WithMany("Historique")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AiSoftwareFactory.Agents.Models.Projet", b =>
                {
                    b.Navigation("Historique");
                });
#pragma warning restore 612, 618
        }
    }
}
